#
# autogenerated by virtualmaster on _virtualmaster_timestamp_
# 
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet static
 address _virtualmaster_ipv4_address_
 gateway _virtualmaster_ipv4_gateway_
 netmask _virtualmaster_ipv4_netmask_
 post-up  ethtool -K eth0 tx off

#
# The line above will disable TCP checksumming which
# might resolve problems for some users.
#
# See http://www.shorewall.net/XenMyWay-Routed.html and search for
# ethtool -K eth0 tx off
#
