Document: virtualmaster
Title: Debian virtualmaster Manual
Author: <insert document author here>
Abstract: This manual describes what virtualmaster is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/virtualmaster/virtualmaster.sgml.gz

Format: postscript
Files: /usr/share/doc/virtualmaster/virtualmaster.ps.gz

Format: text
Files: /usr/share/doc/virtualmaster/virtualmaster.text.gz

Format: HTML
Index: /usr/share/doc/virtualmaster/html/index.html
Files: /usr/share/doc/virtualmaster/html/*.html

  
